"""Extended QA testing patterns — mobile, accessibility, data, integrations."""

from app.intelligence.knowledge_base import TestPattern

EXTENDED_PATTERNS: list[TestPattern] = [
    TestPattern(
        name="Mobile Responsive Layout",
        category="functional",
        trigger_keywords=["mobile", "responsive", "tablet", "viewport", "screen size"],
        steps_template=[
            "Open application on mobile viewport (375x667)",
            "Navigate through primary user flows",
            "Verify layout adapts correctly",
        ],
        expected_template=[
            "UI elements are visible and accessible on mobile",
            "No horizontal scroll or overlapping elements",
            "Touch targets meet minimum size requirements",
        ],
        priority="medium",
        tags=["mobile", "responsive", "ui"],
    ),
    TestPattern(
        name="Accessibility WCAG Compliance",
        category="accessibility",
        trigger_keywords=["accessibility", "wcag", "a11y", "screen reader", "aria", "keyboard"],
        steps_template=[
            "Navigate using keyboard only (Tab, Enter, Escape)",
            "Verify all interactive elements have accessible labels",
            "Run accessibility scan on key pages",
        ],
        expected_template=[
            "All functionality is keyboard accessible",
            "Color contrast meets WCAG AA standards",
            "Screen reader announces content correctly",
        ],
        priority="high",
        tags=["accessibility", "wcag", "compliance"],
    ),
    TestPattern(
        name="Data Validation Boundary",
        category="functional",
        trigger_keywords=["validate", "field", "required", "mandatory", "format", "boundary"],
        steps_template=[
            "Submit form with empty mandatory fields",
            "Submit with boundary values (min, max, max+1)",
            "Submit with invalid format (email, phone, date)",
        ],
        expected_template=[
            "Validation errors displayed for each invalid field",
            "Form is not submitted until all validations pass",
            "Error messages are clear and field-specific",
        ],
        priority="medium",
        tags=["validation", "negative", "boundary"],
    ),
    TestPattern(
        name="Email Notification",
        category="functional",
        trigger_keywords=["email", "notification", "alert", "notify", "mail", "smtp"],
        steps_template=[
            "Trigger an action that sends an email notification",
            "Check email inbox or mail capture service",
            "Verify email content and links",
        ],
        expected_template=[
            "Email is delivered within acceptable time",
            "Email contains correct subject and body content",
            "Links in email are valid and functional",
        ],
        priority="medium",
        tags=["email", "notification", "integration"],
    ),
    TestPattern(
        name="Webhook Integration",
        category="api",
        trigger_keywords=["webhook", "callback", "event", "subscribe", "push notification"],
        steps_template=[
            "Configure webhook endpoint",
            "Trigger the event that fires the webhook",
            "Verify webhook payload received at endpoint",
        ],
        expected_template=[
            "Webhook is delivered with correct HTTP method and headers",
            "Payload matches documented schema",
            "Retry mechanism works on delivery failure",
        ],
        priority="medium",
        tags=["webhook", "api", "integration"],
    ),
    TestPattern(
        name="Multi-Tenant Isolation",
        category="security",
        trigger_keywords=["tenant", "multi-tenant", "organization", "isolation", "workspace"],
        steps_template=[
            "Authenticate as Tenant A user",
            "Attempt to access Tenant B resources via URL manipulation",
            "Verify data boundaries",
        ],
        expected_template=[
            "Tenant A cannot access Tenant B data",
            "403 or 404 returned for cross-tenant access attempts",
            "Audit log records unauthorized access attempt",
        ],
        priority="high",
        tags=["security", "multi-tenant", "isolation"],
    ),
    TestPattern(
        name="Concurrent User Access",
        category="functional",
        trigger_keywords=["concurrent", "simultaneous", "lock", "conflict", "edit same"],
        steps_template=[
            "Two users open the same record simultaneously",
            "Both users attempt to edit and save",
            "Verify conflict resolution behavior",
        ],
        expected_template=[
            "System handles concurrent edits gracefully",
            "Conflict notification shown or optimistic locking applied",
            "No data corruption occurs",
        ],
        priority="medium",
        tags=["concurrency", "functional"],
    ),
    TestPattern(
        name="Export Data",
        category="functional",
        trigger_keywords=["export", "download", "csv", "excel", "pdf", "report"],
        steps_template=[
            "Navigate to exportable data view",
            "Select export format (CSV/PDF/Excel)",
            "Download and verify exported file",
        ],
        expected_template=[
            "File downloads successfully",
            "Exported data matches displayed data",
            "File format is valid and readable",
        ],
        priority="low",
        tags=["export", "functional"],
    ),
    TestPattern(
        name="Import Data",
        category="functional",
        trigger_keywords=["import", "bulk", "csv upload", "migrate", "batch"],
        steps_template=[
            "Prepare valid import file with test data",
            "Upload via import interface",
            "Verify imported records",
        ],
        expected_template=[
            "All valid records imported successfully",
            "Invalid records rejected with clear error report",
            "Import summary shows correct counts",
        ],
        priority="medium",
        tags=["import", "functional", "data"],
    ),
    TestPattern(
        name="Password Reset Flow",
        category="functional",
        trigger_keywords=["reset password", "forgot password", "recover", "password reset"],
        steps_template=[
            "Click 'Forgot Password' link",
            "Enter registered email address",
            "Follow reset link and set new password",
            "Login with new password",
        ],
        expected_template=[
            "Reset email sent to registered address",
            "Reset link expires after configured time",
            "New password works; old password rejected",
        ],
        priority="high",
        tags=["authentication", "security", "password"],
    ),
    TestPattern(
        name="Two-Factor Authentication",
        category="security",
        trigger_keywords=["2fa", "mfa", "two-factor", "otp", "authenticator", "verification code"],
        steps_template=[
            "Enable 2FA on user account",
            "Login with username/password",
            "Enter valid OTP code",
        ],
        expected_template=[
            "2FA setup completes with backup codes generated",
            "Login blocked without valid OTP",
            "Invalid OTP rejected with appropriate error",
        ],
        priority="high",
        tags=["security", "authentication", "2fa"],
    ),
    TestPattern(
        name="GraphQL Query",
        category="api",
        trigger_keywords=["graphql", "query", "mutation", "subscription"],
        steps_template=[
            "Send valid GraphQL query with required variables",
            "Verify response data structure",
            "Send malformed query and verify error handling",
        ],
        expected_template=[
            "Valid query returns expected data",
            "Errors include helpful messages and line numbers",
            "Introspection disabled in production if configured",
        ],
        priority="medium",
        tags=["api", "graphql"],
    ),
    TestPattern(
        name="Rate Limiting",
        category="security",
        trigger_keywords=["rate limit", "throttle", "too many requests", "429", "quota"],
        steps_template=[
            "Send requests up to the configured rate limit",
            "Exceed the rate limit threshold",
            "Verify throttling behavior",
        ],
        expected_template=[
            "Requests within limit succeed normally",
            "429 Too Many Requests returned when limit exceeded",
            "Rate limit headers present in response",
        ],
        priority="medium",
        tags=["security", "api", "rate-limit"],
    ),
    TestPattern(
        name="Audit Trail",
        category="functional",
        trigger_keywords=["audit", "log", "history", "trail", "compliance", "track changes"],
        steps_template=[
            "Perform a tracked action (create, update, delete)",
            "Navigate to audit log/history view",
            "Verify action is recorded with user, timestamp, and details",
        ],
        expected_template=[
            "Audit entry created for the action",
            "Entry includes actor, timestamp, and change details",
            "Audit log is immutable (no edit/delete by regular users)",
        ],
        priority="high",
        tags=["audit", "compliance", "governance"],
    ),
    TestPattern(
        name="Localization i18n",
        category="functional",
        trigger_keywords=["language", "locale", "i18n", "translation", "internationalization", "rtl"],
        steps_template=[
            "Switch application language to alternate locale",
            "Navigate through primary flows",
            "Verify text, dates, and currency formatting",
        ],
        expected_template=[
            "All UI text displayed in selected language",
            "Date and number formats match locale",
            "RTL layout correct for Arabic/Hebrew if supported",
        ],
        priority="low",
        tags=["i18n", "localization", "ui"],
    ),
    TestPattern(
        name="Offline Mode Recovery",
        category="functional",
        trigger_keywords=["offline", "disconnect", "reconnect", "sync", "network loss"],
        steps_template=[
            "Perform actions while connected",
            "Simulate network disconnection",
            "Reconnect and verify data sync",
        ],
        expected_template=[
            "Appropriate offline indicator shown to user",
            "Queued actions sync on reconnect",
            "No data loss during offline period",
        ],
        priority="medium",
        tags=["offline", "mobile", "resilience"],
    ),
    TestPattern(
        name="Database Transaction Rollback",
        category="functional",
        trigger_keywords=["transaction", "rollback", "atomic", "consistency", "commit"],
        steps_template=[
            "Initiate a multi-step transaction",
            "Force failure at intermediate step",
            "Verify database state",
        ],
        expected_template=[
            "Partial changes rolled back on failure",
            "Database remains in consistent state",
            "User notified of transaction failure",
        ],
        priority="high",
        tags=["data", "transaction", "integrity"],
    ),
    TestPattern(
        name="SSO Single Sign-On",
        category="security",
        trigger_keywords=["sso", "saml", "oidc", "single sign", "identity provider", "idp"],
        steps_template=[
            "Navigate to login and select SSO provider",
            "Authenticate via identity provider",
            "Verify session established in application",
        ],
        expected_template=[
            "User redirected to IdP login page",
            "Successful IdP auth creates application session",
            "User attributes mapped correctly from IdP",
        ],
        priority="high",
        tags=["security", "sso", "authentication"],
    ),
    TestPattern(
        name="API Idempotency",
        category="api",
        trigger_keywords=["idempotent", "idempotency", "duplicate request", "retry"],
        steps_template=[
            "Send POST request with idempotency key",
            "Send identical request with same idempotency key",
            "Compare responses",
        ],
        expected_template=[
            "Both requests return same response",
            "No duplicate resource created",
            "Idempotency key honored for configured TTL",
        ],
        priority="medium",
        tags=["api", "reliability"],
    ),
    TestPattern(
        name="Cache Invalidation",
        category="performance",
        trigger_keywords=["cache", "cached", "invalidate", "refresh", "stale"],
        steps_template=[
            "Load data that is cached",
            "Update the underlying data source",
            "Verify cache reflects updated data within TTL",
        ],
        expected_template=[
            "Cached response served on first request",
            "Updated data visible after cache invalidation/TTL",
            "No stale data served beyond configured TTL",
        ],
        priority="medium",
        tags=["performance", "cache"],
    ),
]
